### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by RashmiPandeyatGit** [alyssaq/hough_transform#1]
![errr](https://user-images.githubusercontent.com/22294534/29663676-ed57f212-88e9-11e7-8546-63b0751bb7cc.png)

**Comment by RashmiPandeyatGit** [comment]
![lines](https://user-images.githubusercontent.com/22294534/29663696-09d1fb2c-88ea-11e7-851c-def5e65fa2e3.png)

**Comment by knasim** [comment]
I ended using ```diag_len.asType(np.int64) ``` to convert it from float to a precise integer.

**Comment by alyssaq** [comment]
Thanks for reporting this. This has been fixed now

**Comment by alyssaq** [comment]
@Rashmi002 Since the lines in your image are black, you can pass the following: 
```
hough_line(img, lines_are_white=False)
```
![unknown](https://user-images.githubusercontent.com/2819448/32657962-c342e31e-c652-11e7-8d5c-2e737dab777e.png)
