### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maxfrei750** [alyssaq/hough_transform#10]
Thanks for the awesome work! I'd like to modify it and use it for a project of mine. However, as of now, there is no way for me to do this, since the repo has no license and therefore the default copyright rules apply, which are very restrictive (see https://opensource.stackexchange.com/a/1721). So if you would like to give others the chance to use/modify your work (of course with proper credit), then it would be great, if you could include a more permissive license (e.g. the [MIT license](https://choosealicense.com/licenses/mit/)).

**Comment by alyssaq** [comment]
Added in the README. Enjoy!

**Comment by maxfrei750** [comment]
@alyssaq Nice! Thank you very much! 👍
