### ISSUE TITLE
 Is the unittest.py missing in the hough_transform_test.py ?

### ISSUE THREAD

**Issue by Yangli0505** [alyssaq/hough_transform#3]

**Comment by alyssaq** [comment]
`unittest` is a Python module available in Python 2.7 and 3.5+ https://docs.python.org/2/library/unittest.html

**Comment by Yangli0505** [comment]
Thank you, I got it~ I am a beginner of Python and thank you for your nice reply

发送自 Windows 10 版邮件应用



unittest is a Python module available in Python 2.7 and 2.5+ https://docs.python.org/2/library/unittest.html

**Comment by alyssaq** [comment]
Great! Keep up the learning!
