### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WaldenLeefx** [alyssaq/hough_transform#7]
I'm new to python and use 'python hough_transform.py' then get:
Traceback (most recent call last):
  File "hough_transform.py", line 86, in <module>
    show_hough_line(img, accumulator, save_path='imgs/output.png')
TypeError: show_hough_line() missing 2 required positional arguments: 'thetas' and 'rhos'

**Comment by SydoxX** [comment]
Change line 86 to
`show_hough_line(img, accumulator, thetas, rhos, save_path='imgs/output.png')`

That should fix the issue.

**Comment by SydoxX** [comment]
This was fixed by #6 but is not yet merged.

**Comment by alyssaq** [comment]
Merged now. Thanks :)

**Comment by maxfrei750** [comment]
@alyssaq I think this issue can be closed then, right?
